apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 - ../../base/

nameSuffix: -apac

resources:
- frontend-route.yaml

images:
 - name: mysql
   newName: registry.redhat.io/rhel8/mysql-80
   newTag: 1-152
